language: php
php:
    - 5.6
    - 7.0
    - 7.1
before_install:
    - ln -s yapep_base ../YapepBase
    - composer install --dev
before_script:
    - mysql -u root -e 'create database yapepbase_test; grant all on yapepbase_test.* to 'yapepbase_rw'@'localhost' identified by "test"; grant select on yapepbase_test.* to 'yapepbase_ro'@'localhost' identified by "test";'
    - YAPEPBASE_TEST_MYSQL_RW_HOST=localhost; export YAPEPBASE_TEST_MYSQL_RW_HOST
    - YAPEPBASE_TEST_MYSQL_RW_USER=yapepbase_rw; export YAPEPBASE_TEST_MYSQL_RW_USER
    - YAPEPBASE_TEST_MYSQL_RW_PASSWORD=test; export YAPEPBASE_TEST_MYSQL_RW_PASSWORD
    - YAPEPBASE_TEST_MYSQL_RW_DATABASE=yapepbase_test; export YAPEPBASE_TEST_MYSQL_RW_DATABASE
    - YAPEPBASE_TEST_MYSQL_RO_HOST=localhost; export YAPEPBASE_TEST_MYSQL_RO_HOST
    - YAPEPBASE_TEST_MYSQL_RO_USER=yapepbase_ro; export YAPEPBASE_TEST_MYSQL_RO_USER
    - YAPEPBASE_TEST_MYSQL_RO_PASSWORD=test; export YAPEPBASE_TEST_MYSQL_RO_PASSWORD
    - YAPEPBASE_TEST_MYSQL_RO_DATABASE=yapepbase_test; export YAPEPBASE_TEST_MYSQL_RO_DATABASE
    - YAPEPBASE_TEST_TEMPPATH=/tmp/yapepbase_test/filehandling; export YAPEPBASE_TEST_TEMPPATH
script: phpunit test
